// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-wvN53cfbASgDuBYccnfvZzA5ObtrHSk',
    appId: '1:72616133740:web:a8b2072a72b01cbe130449',
    messagingSenderId: '72616133740',
    projectId: 'johnssonslab-baseline',
    authDomain: 'johnssonslab-baseline.firebaseapp.com',
    storageBucket: 'johnssonslab-baseline.appspot.com',
    measurementId: 'G-L7SHD3PEJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZQBsWhVWRv0Edg8KYiXrGPs5T3Gc_Apk',
    appId: '1:72616133740:android:65cd3344543dc345130449',
    messagingSenderId: '72616133740',
    projectId: 'johnssonslab-baseline',
    storageBucket: 'johnssonslab-baseline.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpi95OTzpKydCTOWRSqvlx9isEo8uM8uM',
    appId: '1:72616133740:ios:ded456ed88652714130449',
    messagingSenderId: '72616133740',
    projectId: 'johnssonslab-baseline',
    storageBucket: 'johnssonslab-baseline.appspot.com',
    iosClientId: '72616133740-8gnd58153b0a0fv6s7couq3fj6ru3kbm.apps.googleusercontent.com',
    iosBundleId: 'com.baithings.toiletsavior',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpi95OTzpKydCTOWRSqvlx9isEo8uM8uM',
    appId: '1:72616133740:ios:f5c4227ccc89f0bf130449',
    messagingSenderId: '72616133740',
    projectId: 'johnssonslab-baseline',
    storageBucket: 'johnssonslab-baseline.appspot.com',
    iosClientId: '72616133740-r57gnvfp7dq8k8krul6kp5qol5io5del.apps.googleusercontent.com',
    iosBundleId: 'com.example.toiletAppRefact',
  );
}
